[2023-02-27T19:51:08.698+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.filter_insert manual__2023-02-27T19:50:59.238270+00:00 [queued]>
[2023-02-27T19:51:08.703+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.filter_insert manual__2023-02-27T19:50:59.238270+00:00 [queued]>
[2023-02-27T19:51:08.704+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T19:51:08.704+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-27T19:51:08.705+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T19:51:08.712+0000] {taskinstance.py:1300} INFO - Executing <Task(BigQueryInsertJobOperator): filter_insert> on 2023-02-27 19:50:59.238270+00:00
[2023-02-27T19:51:08.717+0000] {standard_task_runner.py:55} INFO - Started process 290 to run task
[2023-02-27T19:51:08.720+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'update-filter', 'filter_insert', 'manual__2023-02-27T19:50:59.238270+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/update-filter.py', '--cfg-path', '/tmp/tmpcpza77gf']
[2023-02-27T19:51:08.721+0000] {standard_task_runner.py:83} INFO - Job 62: Subtask filter_insert
[2023-02-27T19:51:08.771+0000] {task_command.py:388} INFO - Running <TaskInstance: update-filter.filter_insert manual__2023-02-27T19:50:59.238270+00:00 [running]> on host d766c014b21e
[2023-02-27T19:51:08.821+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update-filter
AIRFLOW_CTX_TASK_ID=filter_insert
AIRFLOW_CTX_EXECUTION_DATE=2023-02-27T19:50:59.238270+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-27T19:50:59.238270+00:00
[2023-02-27T19:51:08.830+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-02-27T19:51:08.831+0000] {bigquery.py:2635} INFO - Executing: {'query': {'query': 'SELECT id, name FROM `***-gcs-bq.***-gcs-bq.***_dataset.upload` WHERE age > 18', 'destinationTable': {'projectId': '***-gcs-bq', 'datasetId': '***_dataset', 'tableId': '***-gcs-bq.***_dataset.filter'}, 'createDisposition': 'CREATE_IF_NEEDED', 'writeDisposition': 'WRITE_APPEND', 'schema': {'fields': [{'name': 'id', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'name', 'type': 'STRING', 'mode': 'REQUIRED'}]}}}'
[2023-02-27T19:51:08.871+0000] {bigquery.py:1542} INFO - Inserting job ***_update_filter_filter_insert_2023_02_27T19_50_59_238270_00_00_2f69d5f463e704989e24ec9eef2e00e8
[2023-02-27T19:51:09.718+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2636, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2609, in _submit_job
    nowait=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 462, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1545, in insert_job
    job._begin()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1298, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 518, in _begin
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/airflow-gcs-bq/jobs?prettyPrint=false: Invalid table ID "airflow-gcs-bq.airflow_dataset.filter".

Location: None
Job ID: airflow_update_filter_filter_insert_2023_02_27T19_50_59_238270_00_00_2f69d5f463e704989e24ec9eef2e00e8

[2023-02-27T19:51:09.754+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=update-filter, task_id=filter_insert, execution_date=20230227T195059, start_date=20230227T195108, end_date=20230227T195109
[2023-02-27T19:51:09.771+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 62 for task filter_insert (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/airflow-gcs-bq/jobs?prettyPrint=false: Invalid table ID "airflow-gcs-bq.airflow_dataset.filter".

Location: None
Job ID: airflow_update_filter_filter_insert_2023_02_27T19_50_59_238270_00_00_2f69d5f463e704989e24ec9eef2e00e8
; 290)
[2023-02-27T19:51:09.834+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T19:51:09.853+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
