[2023-02-27T22:05:35.828+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.filter_insert manual__2023-02-27T22:05:24.686017+00:00 [queued]>
[2023-02-27T22:05:35.832+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.filter_insert manual__2023-02-27T22:05:24.686017+00:00 [queued]>
[2023-02-27T22:05:35.833+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T22:05:35.833+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-27T22:05:35.834+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T22:05:35.841+0000] {taskinstance.py:1300} INFO - Executing <Task(BigQueryExecuteQueryOperator): filter_insert> on 2023-02-27 22:05:24.686017+00:00
[2023-02-27T22:05:35.846+0000] {standard_task_runner.py:55} INFO - Started process 2478 to run task
[2023-02-27T22:05:35.849+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'update-filter', 'filter_insert', 'manual__2023-02-27T22:05:24.686017+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/update-filter.py', '--cfg-path', '/tmp/tmpeh1og41q']
[2023-02-27T22:05:35.850+0000] {standard_task_runner.py:83} INFO - Job 88: Subtask filter_insert
[2023-02-27T22:05:35.897+0000] {task_command.py:388} INFO - Running <TaskInstance: update-filter.filter_insert manual__2023-02-27T22:05:24.686017+00:00 [running]> on host d766c014b21e
[2023-02-27T22:05:35.943+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update-filter
AIRFLOW_CTX_TASK_ID=filter_insert
AIRFLOW_CTX_EXECUTION_DATE=2023-02-27T22:05:24.686017+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-27T22:05:24.686017+00:00
[2023-02-27T22:05:35.944+0000] {bigquery.py:1077} INFO - Executing: 
        INSERT INTO ***-gcs-bq.***_dataset.filter (id, name)
        SELECT id, name FROM ***-gcs-bq.***_dataset.upload 
[2023-02-27T22:05:35.952+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-02-27T22:05:35.953+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/hooks/bigquery.py:2051: DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
  "This method is deprecated. Please use `BigQueryHook.insert_job` method.", DeprecationWarning

[2023-02-27T22:05:35.991+0000] {bigquery.py:1542} INFO - Inserting job ***_1677535535991171_f7a23a2ae0dd2809c901c2bde81414f3
[2023-02-27T22:05:36.916+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1103, in execute
    encryption_configuration=self.encryption_configuration,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2185, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 462, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1548, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Encountered "" at line 2, column 28.
[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)]

Location: US
Job ID: airflow_1677535535991171_f7a23a2ae0dd2809c901c2bde81414f3

[2023-02-27T22:05:36.925+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=update-filter, task_id=filter_insert, execution_date=20230227T220524, start_date=20230227T220535, end_date=20230227T220536
[2023-02-27T22:05:36.932+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 88 for task filter_insert (400 Encountered "" at line 2, column 28.
[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)]

Location: US
Job ID: airflow_1677535535991171_f7a23a2ae0dd2809c901c2bde81414f3
; 2478)
[2023-02-27T22:05:36.945+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T22:05:36.961+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
