[2023-02-27T21:45:48.620+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.filter_insert manual__2023-02-27T21:32:18.777155+00:00 [queued]>
[2023-02-27T21:45:48.625+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.filter_insert manual__2023-02-27T21:32:18.777155+00:00 [queued]>
[2023-02-27T21:45:48.625+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T21:45:48.625+0000] {taskinstance.py:1280} INFO - Starting attempt 7 of 7
[2023-02-27T21:45:48.626+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T21:45:48.633+0000] {taskinstance.py:1300} INFO - Executing <Task(BigQueryInsertJobOperator): filter_insert> on 2023-02-27 21:32:18.777155+00:00
[2023-02-27T21:45:48.637+0000] {standard_task_runner.py:55} INFO - Started process 1068 to run task
[2023-02-27T21:45:48.640+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'update-filter', 'filter_insert', 'manual__2023-02-27T21:32:18.777155+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/update-filter.py', '--cfg-path', '/tmp/tmp1dy7tyzz']
[2023-02-27T21:45:48.641+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask filter_insert
[2023-02-27T21:45:48.681+0000] {task_command.py:388} INFO - Running <TaskInstance: update-filter.filter_insert manual__2023-02-27T21:32:18.777155+00:00 [running]> on host d766c014b21e
[2023-02-27T21:45:48.719+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update-filter
AIRFLOW_CTX_TASK_ID=filter_insert
AIRFLOW_CTX_EXECUTION_DATE=2023-02-27T21:32:18.777155+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-27T21:32:18.777155+00:00
[2023-02-27T21:45:48.727+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-02-27T21:45:48.728+0000] {bigquery.py:2635} INFO - Executing: {'query': {'query': 'SELECT id, name FROM `***-gcs-bq.***_dataset.upload`', 'destinationTable': {'projectId': '***-gcs-bq', 'datasetId': '***_dataset', 'tableId': 'filter'}, 'createDisposition': 'CREATE_NEVER', 'writeDisposition': 'WRITE_APPEND', 'schema': {'fields': [{'name': 'id', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'name', 'type': 'STRING', 'mode': 'REQUIRED'}]}}}'
[2023-02-27T21:45:48.766+0000] {bigquery.py:1542} INFO - Inserting job ***_update_filter_filter_insert_2023_02_27T21_32_18_777155_00_00_5586cedfa8b0af52f498573c22cd7038
[2023-02-27T21:45:49.785+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2686, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Invalid table name: `airflow-gcs-bq.airflow_dataset.upload`
[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)].

Location: US
Job ID: airflow_update_filter_filter_insert_2023_02_27T21_32_18_777155_00_00_5586cedfa8b0af52f498573c22cd7038

[2023-02-27T21:45:49.796+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=update-filter, task_id=filter_insert, execution_date=20230227T213218, start_date=20230227T214548, end_date=20230227T214549
[2023-02-27T21:45:49.805+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 82 for task filter_insert (400 Invalid table name: `airflow-gcs-bq.airflow_dataset.upload`
[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)].

Location: US
Job ID: airflow_update_filter_filter_insert_2023_02_27T21_32_18_777155_00_00_5586cedfa8b0af52f498573c22cd7038
; 1068)
[2023-02-27T21:45:49.824+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T21:45:49.837+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
